{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "external-targets.fullname" . }}-sa
  labels:
    {{- include "external-targets.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "external-targets.fullname" . }}
  labels:
    {{- include "external-targets.labels" . | nindent 4 }}
rules:
  - verbs:
    - '*'
    apiGroups:
    - '*'
    resources:
    - 'endpoints'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "external-targets.fullname" . }}
  labels:
    {{- include "external-targets.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "external-targets.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "external-targets.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
{{- end }}