apiVersion: v1
kind: Service
metadata:
  name: {{ include "external-targets.fullname" . }}
  labels:
    {{- include "external-targets.labels" . | nindent 4 }}
spec:
  ports:
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.service.metricsPort }}
      protocol: TCP
  type: ClusterIP
